// <auto-generated />
using System;
using Investimentos.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Investimentos.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210627225226_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Investimentos.API.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataVenda")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTipoAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Lucro")
                        .HasColumnType("REAL");

                    b.Property<int>("QuantidadeCompra")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeVenda")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalValorCompra")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorCompra")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValorImposto")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValorLucro")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValorLucroLiquido")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValorTotalVenda")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValorVenda")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValorVendaLiquida")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
